version: '3.8'

services:
  crypto:
    image: harbor.ceasefire.rid-intrasoft.eu/certh_marketplaces/crypto:latest
    labels:
      io.portainer.accesscontrol.teams: /certh
    ports:
      - "16000:16000"
    networks:
      - nlu_network
    depends_on:
      - controller
#    volumes:
#      - ./crypto_tool:/app

  controller:
    image: harbor.ceasefire.rid-intrasoft.eu/certh_marketplaces/controller:latest
    labels:
      io.portainer.accesscontrol.teams: /certh
    ports:
      - "16100:16100"
    networks:
      - nlu_network
#    volumes:
#      - ./controller:/app

  marketplaces:
    image: harbor.ceasefire.rid-intrasoft.eu/certh_marketplaces/marketplaces:latest
    labels:
      io.portainer.accesscontrol.teams: /certh
    ports:
      - "16200:16200"
    networks:
      - nlu_network
    depends_on:
      - controller
 #   volumes:
 #     - ./marketplaces:/app

  pdf_highlight:
    image: harbor.ceasefire.rid-intrasoft.eu/certh_marketplaces/pdf_highlight:latest
    labels:
      io.portainer.accesscontrol.teams: /certh
    restart: unless-stopped
    ports:
      - "36001:36001"
    networks:
      - nlu_network
    depends_on:
      - controller
  #  volumes:
  #    - ./pdf_highlight:/app
  
  reverse_image_search:
    image: harbor.ceasefire.rid-intrasoft.eu/certh_marketplaces/reverse_image_search:latest
    labels:
      io.portainer.accesscontrol.teams: /certh
    restart: unless-stopped
    ports:
      - "36000:36000"
    networks:
      - nlu_network
    depends_on:
      - controller
   volumes:
     - ./reverse_image_search:/app

networks:
  nlu_network:
    external: true
